using System.Globalization;

namespace ProjectSpy.Core;

/// <summary>
/// An absolute point in tactical time, counted in steps since the mission began.
/// </summary>
/// <remarks>
/// <para>
/// A step is 100 ms of simulated time, so there are <see cref="StepsPerSecond"/> of
/// them in a simulated second. This is the second of the two time scales in
/// knowledge.md rule 13, and it exists only inside a tactical mission: the base
/// clock does not advance while tactical time does (rule 13, and the invariant
/// enforced by <see cref="GameSession.AdvanceStrategicTick"/>).
/// </para>
/// <para>
/// Steps are deliberately fine-grained and integer. Perception, noise propagation
/// and alarm bands all resolve per step, and a float here would make "was the guard
/// mid-turn when the door opened" platform-dependent.
/// </para>
/// </remarks>
public readonly record struct Step : IComparable<Step>
{
    /// <summary>Steps in one simulated second.</summary>
    public const int StepsPerSecond = 10;

    /// <summary>Steps in one simulated minute.</summary>
    public const int StepsPerMinute = StepsPerSecond * 60;

    /// <summary>Steps in one simulated hour — that is, in one strategic tick.</summary>
    public const int StepsPerHour = StepsPerMinute * 60;

    /// <summary>The start of a mission.</summary>
    public static readonly Step Zero = new(0);

    /// <summary>Wraps to the raw step counter.</summary>
    public Step(long value) => Value = value;

    /// <summary>The raw step counter.</summary>
    public long Value { get; }

    /// <summary>Whole simulated seconds elapsed since <see cref="Zero"/>.</summary>
    public long Second => Value / StepsPerSecond;

    /// <summary>Elapsed steps inside the current simulated second.</summary>
    public int StepOfSecond => (int)(Value % StepsPerSecond);

    /// <summary>Whole simulated minutes elapsed since <see cref="Zero"/>.</summary>
    public long Minute => Value / StepsPerMinute;

    /// <summary>Elapsed steps inside the current simulated minute.</summary>
    public int StepOfMinute => (int)(Value % StepsPerMinute);

    /// <summary>Builds the step reached after a whole number of seconds.</summary>
    public static Step FromSeconds(long seconds) => new(seconds * StepsPerSecond);

    /// <summary>Builds the step reached after a whole number of minutes.</summary>
    public static Step FromMinutes(long minutes) => new(minutes * StepsPerMinute);

    /// <summary>
    /// The step reached after this many steps. Provided so callers holding a plain
    /// <c>long</c> budget do not have to construct a temporary.
    /// </summary>
    public Step Plus(long steps) => new(Value + steps);

    public static Step operator +(Step a, long steps) => new(a.Value + steps);

    public static Step operator -(Step a, long steps) => new(a.Value - steps);

    public static Step operator -(Step a) => new(-a.Value);

    public static Step operator ++(Step a) => new(a.Value + 1);

    public static Step operator --(Step a) => new(a.Value - 1);

    public static bool operator <(Step a, Step b) => a.Value < b.Value;

    public static bool operator >(Step a, Step b) => a.Value > b.Value;

    public static bool operator <=(Step a, Step b) => a.Value <= b.Value;

    public static bool operator >=(Step a, Step b) => a.Value >= b.Value;

    // == and != are generated by `record struct` from the Value member.

    public int CompareTo(Step other) => Value.CompareTo(other.Value);

    /// <summary>Stable, culture-invariant text form. Used by the save format and tests.</summary>
    public override string ToString() =>
        string.Format(CultureInfo.InvariantCulture, "{0:00}:{1:00}.{2}", Minute, Second % 60, StepOfSecond);
}

/// <summary>
/// The tactical clock. Owns the current <see cref="Step"/> of the running mission.
/// </summary>
/// <remarks>
/// <para>
/// The counterpart to <see cref="StrategicClock"/>. It knows nothing about what a step
/// <em>means</em> — the step pipeline that consumes steps is stage 4c's job, and it
/// subscribes rather than being called from here, for the same reason the tick
/// pipeline is not called from the strategic clock.
/// </para>
/// <para>
/// Subscriptions are methods rather than C# events so the Unity layer can detach
/// cleanly on scene teardown, matching <see cref="StrategicClock"/>.
/// </para>
/// </remarks>
public sealed class TacticalClock
{
    private readonly EventBus _events = new();

    /// <summary>Creates a clock starting at <paramref name="start"/>.</summary>
    public TacticalClock(Step start = default) => Current = start;

    /// <summary>The current absolute step within the mission.</summary>
    public Step Current { get; private set; }

    /// <summary>Total steps advanced since the clock was created.</summary>
    public long StepsElapsed { get; private set; }

    /// <summary>Advances one step and raises <see cref="OnStep"/>.</summary>
    public void Advance() => Advance(1);

    /// <summary>
    /// Advances by <paramref name="steps"/> steps, raising one notification per step.
    /// </summary>
    /// <remarks>
    /// One notification per step rather than one per batch, because a batch advance is
    /// what the simulator does when it runs faster than real time — and every step of
    /// that batch has to be simulated, not just the last.
    /// </remarks>
    public void Advance(long steps)
    {
        if (steps < 0)
            throw new ArgumentOutOfRangeException(nameof(steps), steps, "The clock only moves forward.");

        for (long i = 0; i < steps; i++)
        {
            Current = new Step(Current.Value + 1);
            StepsElapsed++;
            _events.Publish(new StepAdvancedEvent(Current));
        }
    }

    /// <summary>
    /// Advances to an absolute step, used when loading a mid-mission save.
    /// </summary>
    public void SetTo(Step step)
    {
        if (step.Value < Current.Value)
        {
            throw new ArgumentOutOfRangeException(
                nameof(step), step, "Time does not move backwards outside of a load.");
        }

        Advance(step.Value - Current.Value);
    }

    /// <summary>Subscribes to every step.</summary>
    public IDisposable OnStep(Action<StepAdvancedEvent> handler) => _events.Subscribe(handler);
}

/// <summary>Published for every single step advance.</summary>
public sealed record StepAdvancedEvent(Step Step);

/// <summary>
/// Converts elapsed tactical steps into strategic ticks.
/// </summary>
/// <remarks>
/// <para>
/// knowledge.md rule 13: the base clock does not advance during a mission, and on
/// mission end the elapsed steps convert to ticks <em>once</em>. Getting this wrong in
/// either direction is expensive — convert twice and a ten-minute mission costs the
/// player an extra hour of base time; never convert and the world stops while you
/// were away. Hence a named type with a single method rather than an inline division
/// at the call site.
/// </para>
/// <para>
/// One tick is one in-game hour, and there are <see cref="Step.StepsPerHour"/> steps in
/// an hour, so the divisor is 36000.
/// </para>
/// </remarks>
public static class MissionTimeConverter
{
    /// <summary>Steps in one strategic tick: 10 steps per second, 3600 seconds per hour.</summary>
    public const long StepsPerStrategicTick = Step.StepsPerHour;

    /// <summary>
    /// The number of strategic ticks a mission of <paramref name="steps"/> elapsed
    /// steps is worth, rounded up.
    /// </summary>
    /// <remarks>
    /// Rounds up rather than down so that any elapsed mission time costs the player at
    /// least one tick. Rounding down would make the first 59 minutes of every mission
    /// free, which is a systematic gift to the player rather than a rounding detail.
    /// </remarks>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="steps"/> is negative.</exception>
    public static long StepsToStrategicTicks(long steps)
    {
        if (steps < 0)
            throw new ArgumentOutOfRangeException(nameof(steps), steps, "Elapsed steps cannot be negative.");

        return steps / StepsPerStrategicTick + (steps % StepsPerStrategicTick == 0 ? 0 : 1);
    }
}