using System.Globalization;

namespace ProjectSpy.Core;

/// <summary>
/// An absolute point in game time, counted in ticks since the start of the run.
/// </summary>
/// <remarks>
/// <para>
/// A <c>long</c> of ticks is the canonical time representation. A save stores
/// this value; derived values like day and week are recomputed on demand so they
/// can never disagree with each other.
/// </para>
/// <para>
/// Time of day granularity is hourly: <see cref="TicksPerDay"/> ticks make a day
/// and <see cref="TicksPerWeek"/> make a week. This is structural (it defines the
/// calendar) rather than a tuneable, so it lives in code — see knowledge.md rule 3.
/// </para>
/// </remarks>
public readonly record struct Tick : IComparable<Tick>
{
    /// <summary>Ticks in one in-game day.</summary>
    public const int TicksPerDay = 24;

    /// <summary>Ticks in one in-game week.</summary>
    public const int TicksPerWeek = TicksPerDay * 7;

    /// <summary>The start of the run.</summary>
    public static readonly Tick Zero = new(0);

    /// <summary>Wraps to the raw tick counter.</summary>
    public Tick(long value) => Value = value;

    /// <summary>The raw tick counter.</summary>
    public long Value { get; }

    /// <summary>Whole days elapsed since <see cref="Zero"/>.</summary>
    public int Day => (int)(Value / TicksPerDay);

    /// <summary>Hour of day in <c>[0, 24)</c>.</summary>
    public int HourOfDay => (int)(Value % TicksPerDay);

    /// <summary>Whole weeks elapsed since <see cref="Zero"/>.</summary>
    public int Week => (int)(Value / TicksPerWeek);

    /// <summary>
    /// Day of week in <c>[0, 7)</c>, where 0 is the first day of a week.
    /// </summary>
    public int DayOfWeek => (int)((Value / TicksPerDay) % 7);

    /// <summary>Ticks elapsed inside the current week.</summary>
    public int TickOfWeek => (int)(Value % TicksPerWeek);

    /// <summary>Builds the tick at midnight of a given day.</summary>
    public static Tick FromDays(int days) => new((long)days * TicksPerDay);

    /// <summary>Builds a tick from an absolute day and hour.</summary>
    public static Tick FromDayHour(int day, int hourOfDay)
        => new((long)day * TicksPerDay + hourOfDay);

    /// <summary>Midnight of the day this tick falls in.</summary>
    public Tick StartOfDay() => FromDays(Day);

    /// <summary>Midnight of the week this tick falls in.</summary>
    public Tick StartOfWeek() => new((long)Week * TicksPerWeek);

    /// <summary>True when the two ticks fall on different calendar days.</summary>
    public bool IsSameDay(Tick other) => Day == other.Day;

    /// <summary>True when the two ticks fall in different calendar weeks.</summary>
    public bool IsSameWeek(Tick other) => Week == other.Week;

    /// <summary>Signed whole-day gap from this tick to <paramref name="other"/>.</summary>
    public int DaysUntil(Tick other) => other.Day - Day;

    public static Tick operator +(Tick a, int ticks) => new(a.Value + ticks);
    public static Tick operator -(Tick a, int ticks) => new(a.Value - ticks);
    public static Tick operator +(Tick a, Tick b) => new(a.Value + b.Value);
    public static Tick operator -(Tick a, Tick b) => new(a.Value - b.Value);
    public static Tick operator -(Tick a) => new(-a.Value);
    public static Tick operator ++(Tick a) => new(a.Value + 1);
    public static Tick operator --(Tick a) => new(a.Value - 1);

    // == and != are generated by `record struct` from the Value member; redefining
    // them here would be a compile error (CS0111).

    public static bool operator <(Tick a, Tick b) => a.Value < b.Value;
    public static bool operator >(Tick a, Tick b) => a.Value > b.Value;
    public static bool operator <=(Tick a, Tick b) => a.Value <= b.Value;
    public static bool operator >=(Tick a, Tick b) => a.Value >= b.Value;

    public int CompareTo(Tick other) => Value.CompareTo(other.Value);

    /// <summary>Stable, culture-invariant text form. Used by the save format and tests.</summary>
    public override string ToString() =>
        string.Format(CultureInfo.InvariantCulture, "D{0} {1:00}:00 (W{2})", Day, HourOfDay, Week);
}
